# Generated by Django 5.1.1 on 2024-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_education_model_experience_model_interest_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermidiate_skill_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience_model',
            name='company',
        ),
        migrations.RemoveField(
            model_name='experience_model',
            name='description',
        ),
    ]
